name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - tensorflow
  - graphviz
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - xgboost
    - matplotlib
    - plotly
    - sklearn
    - scipy
    - keras
    - pydot
    - jupyter-tensorboard
    - pytz

