name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.8
  - graphviz
  - pip
  - pip:
    - numpy
    - pandas
    - keras==2.3.1
    - tensorflow>=2.0
    - nbgitpuller
    - nbformat<5
    - pytz
    - sphinx-gallery
    - xgboost
    - matplotlib
    - plotly
    - scikit-learn==0.21.2
    - scipy
    - pydot
    - jupyter
    - jupyter-tensorboard
