name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.8
  - graphviz
  - pip
  - pip:
    - numpy
    - pandas
    - joblib
    - tensorflow==2.2.2
    - tensorboard==2.2
    - jupyter_tensorboard
    - pytz
    - xgboost
    - matplotlib
    - plotly
    - scikit-learn
    - pydot
    - jupyter
    - requests
