name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - graphviz
  - pip
  - pip:
    - numpy
    - pandas
    - keras==2.3.1
    - tensorflow==2.0
    - nbgitpuller
    - pytz
    - sphinx-gallery
    - xgboost
    - matplotlib
    - plotly
    - sklearn==0.22.2 
    - scipy
    - pydot
    - jupyter
    - jupyter-tensorboard
